# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MATH 2530
full_title: MATH 2530 Introductory Data Science, Ohio University, Spring 2025-26
email: clarkw3@ohio.edu
description: >- # this means to ignore newlines until "baseurl:"
  Students learn the basics of data acquisition, organization, and analysis; acquire hands-on experience with statistical estimation and inference, data modelling, and visualization; and explore machine learning applications, data privacy, and ethics.
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "/MATH2530_Spring25-26" # the subpath of your site, e.g. /blog
url: "https://data-ohio.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: wiclark

# DS-100 customization to put in sidebar
# When tried by using DS-100 default.html layout, broke build
# in just-the-docs nav.html
#nav_links:
#  Links:
#    Textbook:
#      - 'https://data-ohio.github.io/introductory-data-science/'

### appear after search bar in upper right
aux_links:
  'Textbook':
    - 'https://data-ohio.github.io/introductory-data-science/'

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.3.3

# Collections for web data
collections:
  modules:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: modules
    values:
      layout: module

# empty the footer
#footer:  ""
